vim.api.nvim_create_user_command("JekyllDraft", function()
  require("jekyll").create_draft()
end, {})
vim.api.nvim_create_user_command("JekyllPost", function()
  require("jekyll").create_post()
end, {})
vim.api.nvim_create_user_command("JekyllPromote", function()
  require("jekyll").promote_draft()
end, {})
vim.api.nvim_create_user_command("JekyllNote", function()
  require("jekyll").create_note()
end, {})
